### ISSUE TITLE
Networking LSL AvgBandPower: only one band value is sent

### ISSUE THREAD

**Issue by chris-zielinski** [OpenBCI/OpenBCI_GUI#1098]
## Problem

When using the LSL networking protocol to send the AvgBandPower, the data output is only one single value.

## Expected 

Like for the other protocol, the expected output should be the 5 avg power value (one per band).
In the W_Networking.pde/sendNormalizedPowerBandData function,  the loop across each frequency band is missing for the LSL case.

## Operating System and Version
Windows

## GUI Version
5.1.0

## Running standalone app
downloaded app

## Type of OpenBCI Board
Synthetic

## Are you using a WiFi Shield?
No

## Console Log

Thank you!

**Comment by retiutut** [comment]
Confirmed using Networking test kit. When this metric was added it was in support of OpenBCI team using UDP. Thanks for bringing this oversight to our attention, we will include the fix in the next version of the GUI.

**Comment by retiutut** [comment]
Actually the code in `sendNormalizedPowerBandData()` is fine, since we pass in a single dimension array, which is a valid option for LSL push_sample. What's wrong is the number of channels per sample, which should be 5 instead of 1.

![Screen Shot 2023-01-11 at 9 08 52 PM](https://user-images.githubusercontent.com/25914123/211966681-ab54f70d-497c-48e4-8e9d-e99a4b55bb35.png)
