### ISSUE TITLE
Samples dropped during LSL communication to Matlab

### ISSUE THREAD

**Issue by armengol** [OpenBCI/OpenBCI_GUI#1103]
Hello,

I have a Ganglion board and I'm trying to send data from OpenBCI GUI to Matlab via LSL. The amount of datapoints received during a period of time (ex: 5 seconds) doesn't match with the supposed number of datapoints that I should receive with the given sampling rate (200Hz * 5 seconds = 1000 datapoints, and I get around ~550 datapoints). Is there an issue with LSL?

Thanks!

**Comment by retiutut** [comment]
Hello @armengol. Thanks for making this issue, though you will need to remake it using the now updated Issue Template. Thanks.

There is not enough required information in order to proceed investigating this, though I can say right now that we have validated our usage of LSL using a test kit that is included in this repo.
