### ISSUE TITLE
possible anomalous impedance measure fluctuations seen using the impedance widget

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/OpenBCI_GUI#1121]
## Problem

See this Forum post:
https://openbci.com/forum/index.php?p=/discussion/3527/gelfree-electrode-cap-impedance-fluctuation

## Expected 

The user in the above Forum post, is expecting a previous channel impedance to remain the same after selecting a subsequent channel to be measured. Instead, the previous impedance suddenly jumps up. 

## Operating System and Version

macOS/Windows/Linux - Example: MacOS 10.15.7

## GUI Version

The version is displayed on startup and at the top of every Console Log.

## Are you running the downloaded app or from Processing/VSCode?

The downloaded app or compiling and running the code.

## Type of OpenBCI Board

Cyton

## Console Log and Screenshots

Screenshots shown on the Forum post.

**Comment by retiutut** [comment]
I was not able to replicate or discover any issues with the Cyton Signal widget using the latest in-progress branch using GUI v6.0.0-alpha.2.

Users should be patient with Cyton Signal Check Widget since it needs to send a few commands to the board. The `Check All Channels` function will always resume where it left off. 

Next progress for this widget will be completed with:
- https://github.com/OpenBCI/OpenBCI_GUI/issues/1058
- https://github.com/OpenBCI/OpenBCI_GUI/issues/1134
