### ISSUE TITLE
Modify GUI Headmap Electrode Positions

### ISSUE THREAD

**Issue by CelticHarp** [OpenBCI/OpenBCI_GUI#138]
It would be nice the file 'electrode_positions_default.txt' to be editable and readable by the GUI in order to change the default electrode positions that correspond to the GUI headmap.
Maybe at a later improvement we could choose from a picture the positions and the file to be updated automatically with the coordinations.
In any case a documentation of this capability would be essential.

Reported by: compmonks, jussijaatinen, celticharp

Thank you!

**Comment by compmonks** [comment]
yes, it would be nice to have a text file with 10-20 coordinates adjusted for the GUI along with a way to label electrodes with their correct name (Fz, FCz, Oz, O3, ...) instead of their index (1,2,3,...). I guess most users would find it also very useful  and time-saving :)

**Comment by aj-ptw** [comment]
@conorrussomanno wrote some code for this once upon a time

**Comment by aj-ptw** [comment]
closed by #152

**Comment by emolyzr** [comment]
Hi,
thanks for adding the drag and drop option. Unfortunately, this doesn't solve the issue. One can move the electrode positions, but this won't affect the calculation of the scalp distribution in any meaningful way.
![unbenannt](https://user-images.githubusercontent.com/35568338/35920879-6facdc02-0c19-11e8-9022-e1ad00da1f16.png)

In addition, it's not possible to save the configuration, so that upon reloading the GUI one has to move the nods again.

Any help would be highly appreciated.

**Comment by emolyzr** [comment]
As a workaround to solve this issue: 
1.) Just go to ~\OpenBCI_GUI\data 
2.) Open the file electrode_positions_default.txt and change the settings according to your setup (You may wish to make a backup of the original file first). 
3.) When starting the GUI, the head plot widget will always read out this file. 

It would be convenient, to know the coordinates of the other nodes of Ultracortex Headset, however by playing around one should get the right estimates oneself.

**Comment by yidilozdemir** [comment]
I have the latest version of the OpenBCI_GUI, and here I cannot find this location ~\OpenBCI_GUI\data. What is the current fix for the issue described?
