### ISSUE TITLE
Ganglion unable to detect/pair

### ISSUE THREAD

**Issue by ssman783** [OpenBCI/OpenBCI_GUI#413]
Hello,

i am unable to detect ganglion board in OpenBCI_GUI 3.3.2 on Win 10 64bit, LED on board is still blinking indicating its not paired. I followed guide, installed drivers, files are in recomended folder, both "running as administrator", Zadig used to replace driver on dongle successfully, yet the device seems invisible.

USB dongle:
Bluetooth 4.0 USB dongle BT430     CI-479       by connectIT

When i installed CSR harmony which is supported, using that i am able to detect ganglion board, but pairing always fail, due not confirming pairing code on ganglion board, but also if it was successfull, after installing Zadig driver replacement, csr harmony is unable to detect dongle, so i am not sure if connection would last anyway. 

Any help?

**Comment by daniellasry** [comment]
@ssman783 Sorry you're getting such a late response on this. Unfortunately we dropped support for CSR/Zadig dongles a while back. The latest GUI that support them is v3.4.0. Maybe try that one?

Otherwise, the easiest way forward is to get a [Ganglion Dongle](https://shop.openbci.com/collections/frontpage/products/ganglion-dongle?variant=15473352605768) or a BLED112 dongle from digikey.
