### ISSUE TITLE
OSC data stream not working

### ISSUE THREAD

**Issue by jzingh98** [OpenBCI/OpenBCI_GUI#463]
## Problem
I'm using the OpenBCI HUB and GUI with a Ganglion board. Running it as administrator. I'm trying to get it to send OSC data to neuromore but it was unable to detect any OSC at the specified port and address. Also downloaded the Kasper Kaperman OSC data viewers, and it showed no incoming data stream at the specified port and address.

## Expected 

In a perfect world, what do you expect to happen.

## Operating System and Version
Windows 64 bit

## GUI Version
4.0.3

## Running standalone app

Are you running the downloaded app or are you running from Processing 3

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
I was not able to replicate this issue. [OSC](https://en.wikipedia.org/wiki/Open_Sound_Control) is working perfectly, and has been for as long as I have used the GUI.

Tested using Windows 10, GUI 4.1.0, and https://www.kasperkamperman.com/blog/processing-code/osc-datamonitor/

![Capture](https://user-images.githubusercontent.com/25914123/55014526-1d433a80-4fb9-11e9-8bed-6020d9b10b4c.PNG)

>  Also downloaded the Kasper Kaperman OSC data viewers, and it showed no incoming data stream at the specified port and address.

This would only happen if the port an address are incorrect. All you need to get OSC working is the correct IP and port, as seen in the above screenshot.

This issue can be closed.

**Comment by jzingh98** [comment]
I think you might be right about it being a port or IP issue. Not working on OpenVibe either.

It's a Ganglion board, Windows 10, and currently using latest version of each Hub, GUI, and OpenVibe

![Screenshot (85)](https://user-images.githubusercontent.com/38117269/55030904-a151ee00-4fca-11e9-87f5-83810b8c2284.png)

**Comment by retiutut** [comment]
That's not how you connect the GUI to OpenVibe. That driver you have selected in OpenVibe is for the Cyton only, and does not require the GUI.

**Comment by jzingh98** [comment]
Okay that makes sense, thank you for clarifying.  What did you mean by Run the GUI from Processing?

**Comment by retiutut** [comment]
@jzingh98 This is a place for issues with GUI, not a place for step-by-step instructions. For this reason, there is a wealth of information in the Docs. https://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-running-the-openbci-gui-from-the-processing-ide

There is no problem with the GUI related to the issue of "OSC data stream not working" because it works just fine. **This issue can be closed.**

**Comment by retiutut** [comment]
@jzingh98 Once you find a setup that you think will work for what you want to do, work hard for a day or two to make sure you've done everything based on what you can read.

Example: I like to run the GUI and stream via OSC to [Max/MSP](https://en.wikipedia.org/wiki/Max_(software)) to control sounds/lights/etc.

It seems like researchers prefer LSL.

If something is legitimately broken, let us know and we will get to the bottom of it!

**Comment by retiutut** [comment]
@jzingh98 If you really want to use OpenVibe, I can help setup the example file!

**Comment by retiutut** [comment]
@jzingh98 Here you go! Going to provide a short how to right now since it doesn't seem to be in the Docs:

1. Startup GUI from Processing and connect to Ganglion
2. Select LSL in the Networking Widget (see screenshot)
![Capture2](https://user-images.githubusercontent.com/25914123/55034165-d5d1a400-4fe2-11e9-8de0-b66a515d0342.PNG)

3.
