### ISSUE TITLE
Open BCI abnormally high amplitude very often

### ISSUE THREAD

**Issue by rakansha** [OpenBCI/OpenBCI_GUI#554]
## Problem

I have been using Open BCI Ganglion for quite a long time now(7 months). I purchased a new board and started using it a month ago. I am using Gold cup electrodes. Since a week it has started giving more amplifier saturations and sometimes it samples very slow. Typically, now the data can look like, after filtering and subtracting 1 and 2, 3 and 4 to get C3 and C4 respectively in the figure:
![Screenshot (32)](https://user-images.githubusercontent.com/12885341/60624224-05aff500-9de5-11e9-8200-9dcfffec2169.png)

in case of slowing down.
In case of amplifier saturations that I am talking about, the high amplitude double spike on left:
![Screenshot (35)](https://user-images.githubusercontent.com/12885341/60624300-36902a00-9de5-11e9-86fe-eeebe3f28326.png)

It would have been acceptable if it happened rarely, but now it turns up every minute or so and I am using it for an important clinical study. This is affecting my project now. any ideas what is the problem here? I am using Lab Streaming Layer to stream it and reading it in Open Vibe. I would also like to mention, sometimes channel 1 and 2 are noisier than the others or channel 1 is the noisiest, even when impedances are fairly similar on all electrodes. I understand in a clinical therapeutic environment it can pick up noises from some electrical and magnetic huge devices, but this was happening in other environments with nothing to cause abnormailty. And it was not happening before.
## Expected 

It should stream normally, shouldn't saturate when I am recording EEG. I am using all 4 channels and D_G at forehead, Reference behind ear

## Operating System and Version

Windows 10

GUI Version latest 4.1.2 Beta

The version is displayed on startup.

Running standalone app

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here

**Comment by retiutut** [comment]
This has nothing to do with the OpenBCI GUI. There is no bug or issue here.

**Comment by retiutut** [comment]
If this Ganglion is a legitimate OpenBCI board, you can contact support.

**Comment by retiutut** [comment]
This is probably caused by connection issues. The Ganglion boards are extremely reliable and resilient.

**Comment by retiutut** [comment]
I've recently covered a ganglion in aluminum foil and walked around the house. There are no spikes or abnormally high amplitudes if no electrodes are connected.

**Comment by jps2000** [comment]
I also found similar spikes long time ago and want to share my experiences with it.
I 3d print a box for the ganglion in ABS. It works fine even without electrodes connected. then I noticed when touch or rub the box with  hands or garmet (wool, hair!) then I got such spikes / saturation.
This was caused by electrical charge of the ABS. 
Solution was to paint the inside of the box with conductive lacquer and connect it to ground. I leave  the part of the box close to  the Simblee module free  of course.

I used this copper spray:  
https://www.distrelec.de/de/leitfaehiger-beschichtungs-200-ml-kontakt-chemie-emi-35-200-ml-ml/p/30025848
I did not spray but  paint it with a small brush instead. (shake well, spray it into a small cup and then paint richly).
When dry you achieve <100 Ohms or better.
